#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 01, 2018 11:20:46 PM IST  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gettowork_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = GetToWORK_By_Team_VISION (root)
    gettowork_support.init(root, top)
    root.mainloop()

w = None
def create_GetToWORK_By_Team_VISION(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = GetToWORK_By_Team_VISION (w)
    gettowork_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_GetToWORK_By_Team_VISION():
    global w
    w.destroy()
    w = None


class GetToWORK_By_Team_VISION:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Trebuchet MS} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Trebuchet MS} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("530x226+444+182")
        top.title("GetToWORK By Team VISION")
        top.configure(background="#ffffff")



        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.0, rely=0.177, relwidth=1.075)

        self.tLa41 = ttk.Label(top)
        self.tLa41.place(relx=0.264, rely=0.044, height=28, width=259)
        self.tLa41.configure(background="#e3f4ff")
        self.tLa41.configure(foreground="#000000")
        self.tLa41.configure(font=font10)
        self.tLa41.configure(relief=FLAT)
        self.tLa41.configure(text='''GetToWORK By Team VISION''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.019, rely=0.31, height=24, width=42)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Site :''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.113, rely=0.31,height=20, relwidth=0.347)
        self.Entry1.configure(background="#e3f4ff")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=184)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.113, rely=0.575, height=24, width=61)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#e3f4ff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Add>''')
        self.Button1.configure(width=61)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.264, rely=0.575, height=24, width=57)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#e3f4ff")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Remove>''')
        self.Button2.configure(width=57)

        self.Message1 = Message(top)
        self.Message1.place(relx=0.094, rely=0.442, relheight=0.102
                , relwidth=0.289)
        self.Message1.configure(background="#ffffff")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Ex : www.facebook.com''')
        self.Message1.configure(width=153)

        self.Button3 = Button(top)
        self.Button3.place(relx=0.113, rely=0.752, height=24, width=137)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#e3f4ff")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''List Of Blocked Sites''')
        self.Button3.configure(width=137)

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.509, rely=0.177, relheight=1.018)
        self.TSeparator2.configure(orient="vertical")

        self.Label1_1 = Label(top)
        self.Label1_1.place(relx=0.642, rely=0.265, height=24, width=112)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#ffffff")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font11)
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Working Time :''')
        self.Label1_1.configure(width=112)

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.623, rely=0.442, height=19, width=54)
        self.TLabel1.configure(background="#ffffff")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Starts At :''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.755, rely=0.442,height=20, relwidth=0.083)
        self.Entry2.configure(background="#e3f4ff")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=44)

        self.TLabel1_2 = ttk.Label(top)
        self.TLabel1_2.place(relx=0.623, rely=0.619, height=19, width=59)
        self.TLabel1_2.configure(background="#ffffff")
        self.TLabel1_2.configure(foreground="#000000")
        self.TLabel1_2.configure(font="TkDefaultFont")
        self.TLabel1_2.configure(relief=FLAT)
        self.TLabel1_2.configure(text='''Ends At :''')
        self.TLabel1_2.configure(width=59)

        self.Entry2_3 = Entry(top)
        self.Entry2_3.place(relx=0.755, rely=0.619,height=20, relwidth=0.083)
        self.Entry2_3.configure(background="#e3f4ff")
        self.Entry2_3.configure(disabledforeground="#a3a3a3")
        self.Entry2_3.configure(font="TkFixedFont")
        self.Entry2_3.configure(foreground="#000000")
        self.Entry2_3.configure(highlightbackground="#d9d9d9")
        self.Entry2_3.configure(highlightcolor="black")
        self.Entry2_3.configure(insertbackground="black")
        self.Entry2_3.configure(selectbackground="#c4c4c4")
        self.Entry2_3.configure(selectforeground="black")

        self.Button3_4 = Button(top)
        self.Button3_4.place(relx=0.604, rely=0.752, height=24, width=137)
        self.Button3_4.configure(activebackground="#d9d9d9")
        self.Button3_4.configure(activeforeground="#000000")
        self.Button3_4.configure(background="#e3f4ff")
        self.Button3_4.configure(disabledforeground="#a3a3a3")
        self.Button3_4.configure(foreground="#000000")
        self.Button3_4.configure(highlightbackground="#d9d9d9")
        self.Button3_4.configure(highlightcolor="black")
        self.Button3_4.configure(pady="0")
        self.Button3_4.configure(text='''Set Time''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup2(event, *args, **kwargs):
        Popupmenu2 = Menu(root, tearoff=0)
        Popupmenu2.configure(activebackground="#f9f9f9")
        Popupmenu2.configure(activeborderwidth="1")
        Popupmenu2.configure(activeforeground="black")
        Popupmenu2.configure(background="#d9d9d9")
        Popupmenu2.configure(borderwidth="1")
        Popupmenu2.configure(disabledforeground="#a3a3a3")
        Popupmenu2.configure(font="{Segoe UI} 9")
        Popupmenu2.configure(foreground="black")
        Popupmenu2.post(event.x_root, event.y_root)

    @staticmethod
    def popup3(event, *args, **kwargs):
        Popupmenu3 = Menu(root, tearoff=0)
        Popupmenu3.configure(activebackground="#f9f9f9")
        Popupmenu3.configure(activeborderwidth="1")
        Popupmenu3.configure(activeforeground="black")
        Popupmenu3.configure(background="#d9d9d9")
        Popupmenu3.configure(borderwidth="1")
        Popupmenu3.configure(disabledforeground="#a3a3a3")
        Popupmenu3.configure(font="{Segoe UI} 9")
        Popupmenu3.configure(foreground="black")
        Popupmenu3.post(event.x_root, event.y_root)






if __name__ == '__main__':
    vp_start_gui()



